### ISSUE TITLE
Help Masung's OS

### ISSUE THREAD

**Issue by HurSungYun** [ProjectKKR/Oblivion#1]

**Comment by rhs0266** [comment]
Turn it to public

**Comment by HurSungYun** [comment]
Come 301-314 and help me

2016년 5월 22일 일요일, rhs0266notifications@github.com님이 작성한 메시지:

> Turn it to public
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ProjectKKR/Oblivion/issues/1#issuecomment-220816622

## 

허성연 (Hur SungYun)
Department of Computer Science and Engineering
Seoul National University
ethan0311@gmail.com

**Comment by rhs0266** [comment]
Jeol Rae Jeol Rae

**Comment by KimHyeonwoo** [comment]
Fighting Masung :)

**Comment by HurSungYun** [comment]
T.T
